{
 "title": "Solana Exporter",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(solana_active_validators, service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Nodes and cluster statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node versions",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "solana_node_versions", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Number of nodes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "solana_nodes" }
   ]
  },
  {
   "title": "Transactions per second",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(solana_transaction_count[5m])"
    }
   ]
  },
  {
   "title": "Average slot time in epoch",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "solana_average_slot_time" }
   ]
  },
  { "title": "Decentralisation Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Active validators by ISP",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_active_validators_isp_count",
     "legendFormat": "{{isp_name}}"
    }
   ]
  },
  {
   "title": "Actived stake by ISP",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_active_validators_isp_stake",
     "legendFormat": "{{isp_name}}"
    }
   ]
  },
  {
   "title": "Activated stake by Datacenter",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_active_validators_dc_stake",
     "legendFormat": "{{dc_identifier}}"
    }
   ]
  },
  { "title": "Solana Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Skipped slot percentages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "solana_skipped_slot_percent", "legendFormat": "{{pubkey}}" }
   ]
  },
  {
   "title": "Skipped slot average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(solana_skipped_slot_percent)"
    }
   ]
  },
  {
   "title": "validator desync",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "solana_validator_last_vote - on(service) group_left() max by(env, service) (solana_validator_last_vote{service=~\"$service\"}) > -500000",
     "legendFormat": "{{pubkey}}"
    }
   ]
  },
  {
   "title": "rate(max(last_voted))",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(max by(env, service) (solana_validator_last_vote{service=~\"$service\"})[1m:])"
    }
   ]
  },
  {
   "title": "active / delinquent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "solana_active_validators{service=~\"$service\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "max(root_slot)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(solana_validator_root_slot{service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "max(last_voted)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 50 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(solana_validator_last_vote{service=~\"$service\"})"
    }
   ]
  }
 ]
}