{
 "title": "Solana Exporter",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(solana_active_validators, service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Decentralisation Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active validators by ISP",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "solana_active_validators_isp_count",
     "legendFormat": "{{isp_name}}"
    }
   ]
  },
  {
   "title": "Actived stake by ISP",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "solana_active_validators_isp_stake",
     "legendFormat": "{{isp_name}}"
    }
   ]
  },
  {
   "title": "Activated stake by Datacenter",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "solana_active_validators_dc_stake",
     "legendFormat": "{{dc_identifier}}"
    }
   ]
  },
  { "title": "Solana Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "validator desync",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solana_validator_last_vote - on(service) group_left() max by(env, service) (solana_validator_last_vote{service=~\"$service\"}) > -500000"
    }
   ]
  },
  {
   "title": "rate(max(last_voted))",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(max by(env, service) (solana_validator_last_vote{service=~\"$service\"})[1m:])"
    }
   ]
  },
  {
   "title": "active / delinquent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solana_active_validators{service=~\"$service\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "max(root_slot)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(solana_validator_root_slot{service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "max(last_voted)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(solana_validator_last_vote{service=~\"$service\"})"
    }
   ]
  }
 ]
}